blank_issues_enabled: true
contact_links:
  - name: Slack Community
    url: https://join.slack.com/t/tremor-community/shared_invite/zt-1u8jqmcmq-Fdr9B6MbnO7u8FkGh~2Ylg
    about: Please ask and answer usage questions here.
